data:
  input_dir: "data/raw"
  output_dir: "data/processed"
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  random_seed: 42

preprocessing:
  frame_extraction:
    fps: 5
    max_frames: 300
    min_frames: 10

  face_detection:
    detector: "opencv"  # Options: "dlib", "opencv"
    min_face_size: 100
    margin: 0.2  # Margin around detected face as percentage of face size

  image_processing:
    target_size: [224, 224]
    normalization:
      mean: [0.485, 0.456, 0.406]  # ImageNet mean
      std: [0.229, 0.224, 0.225]   # ImageNet std
    augmentations:
      enabled: true
      horizontal_flip: true
      rotation_range: 15
      brightness_range: [0.8, 1.2]
      contrast_range: [0.8, 1.2]

  audio_processing:
    sample_rate: 16000
    n_mels: 80
    n_fft: 2048
    hop_length: 512

output:
  format: "lmdb"  # Options: "hdf5", "numpy", "torch", "lmdb"
  batch_size: 100
  compression: "gzip"
  compression_level: 9
  
  # LMDB-specific configuration
  lmdb:
    map_size_gb: 10  # Maximum database size in GB
    max_readers: 1024
    create_indexes: true  # Whether to create indexes for efficient querying
    index_fields: ["label", "category", "method"]  # Fields to index 