data:
  input_dir: "data/raw"
  output_dir: "data/processed"
  train_split: 0.8
  val_split: 0.2
  random_seed: 42

preprocessing:
  face_detection:
    min_face_size: 100
    margin: 0.2  # Margin around detected face as percentage of face size

  image_processing:
    target_size: [ 224, 224 ]
    normalization:
      mean: [ 0.485, 0.456, 0.406 ]  # ImageNet mean
      std: [ 0.229, 0.224, 0.225 ]   # ImageNet std

  audio_processing:
    enabled: true
    sample_rate: 16000
    n_mels: 64
    n_fft: 1024
    hop_length: 256
    mel_overlap_ratio: 0.5  # Overlap ratio for mel spectrograms (0.0-1.0)

output:
  # WebDataset configuration
  webdataset:
    prefix: "shard"
    max_shard_size_mb: 1024
    image_codec: "webp"     # "webp" or "jpeg"
    image_quality: 90        # 1-100
    index_filename: "index.csv"
    clip_length: 16
    clip_stride: 8